<?php

/**
 * Magictoolbox configurable options template for Magento store.
 * Allow use MagicTools with product attributes
 * @mail support@magictoolbox.com
 */

$_product    = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <dl>
    <?php foreach($_attributes as $_attribute): ?>
        <dt><label><?php echo $_attribute->getLabel() ?><span class="required">&nbsp;*</span></label></dt>
        <dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
          <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select" onchange="MagicToolboxChangeOptionConfigurable(this, '<?php echo strtolower(trim($_attribute->getLabel())); ?>');">
            <option><?php echo $this->__('Choose ' . $_attribute->getLabel()) ?></option>
          </select>
        </dd>
    <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        var spConfig = new Product.Config(<?php echo $this->getJsonConfig() ?>);

        // Ruben - custom code her to replace choose an option..

        //Configurable options select
            jQuery("fieldset.product-options > ol.form li").each(
              function(i)
              {
                jQuery(this).find("label").find("span").remove().end().hide(); //Hide labels and remove required text
                jQuery(this).find("select > option:first").html("Choose " + jQuery(this).find("label").html() + "&hellip;"); //Set first option text to value of label
              }
            );

            //Custom options select
            jQuery("fieldset.product-options > dl").each(
              function()
              {
                jQuery(this).find("dt").find("span").remove().end().hide(); //Hide labels and remove required text
                jQuery(this).find("select > option:first").html("Choose " + jQuery(this).find("dt").html() + "&hellip;"); //Set first option text to value of label
              }
            );
            
    </script>
<?php endif;?>
