<?php

    $helper = Mage::helper('magiczoomplus/settings');
    if($helper->isModuleEnabled() && $helper->isModuleOutputEnabled()) {
        //$moduleName = $this->getRequest()->getModuleName();       //catalog   review  catalog     cms     catalogsearch   catalogsearch
        //$this->getRequest()->getRouteName()                       //catalog   review  catalog     cms     catalogsearch   catalogsearch
        $controllerName = $this->getRequest()->getControllerName(); //product   product category    index   result          advanced
        $actionName = $this->getRequest()->getActionName();         //view      list    view        index   index           result

        //$page = ($controllerName == 'product')?'product':'category';
        //$productPage = ($controllerName == 'product') && ($actionName == 'view');
        $productPage = false;
        if($controllerName == 'product') {
            $page = 'product';
            if($actionName == 'view') {
                $productPage = true;
            }
        } else {
            $page = 'category';
        }

        $tool = $helper->loadTool($page);
        if($tool->params->checkValue('use-effect-on-'.$page.'-page', 'Yes')) {

            if($productPage && $tool->params->checkValue('selector-position', array('left', 'right'))) {
?>
<style type="text/css">
    div.MagicToolboxWrapper {float: left; width: <?php echo $tool->params->getValue('thumb-max-width'); ?>px; }
    .product-view .product-img-box .more-views li { clear: both; }
    div.MagicToolboxSelectorsContainer { float: left; }
</style>
<?php
            }


            echo $tool->headers(str_replace('/magiczoomplus.js', '', $this->getSkinUrl('js/magiczoomplus.js')), str_replace('/magiczoomplus.css', '', $this->getSkinUrl('css/magiczoomplus.css')));


            if($productPage) {
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/magictoolbox_utils.js'); ?>"></script>
<script type="text/javascript">
    var magicToolboxOptionTitles = ['<?php echo strtolower(trim(preg_replace('/\s*,\s*/is', '\',\'', $tool->params->getValue('option-associated-with-images')))); ?>'];


    var MagicToolbox_click = '<?php echo strtolower($tool->params->getValue('swap-image')); ?>';


    $mjs(window).je1('load', function() {
        MagicToolboxPrepareOptions();
    });


</script>
<?php
            }

        }
    }

?>