<?php

/**
 * Magictoolbox product list template for Magento store.
 * Allow use MagicTools on product list page.
 * @mail support@magictoolbox.com
 */

    foreach ($_productCollection as $_product) {

        $_product = Mage::getModel('catalog/product')->load($_product->getId());

        if($_product->getImage() && $_product->getImage() != 'no_selection') {
            $title = $this->htmlEscape($_product->getName());
            $description = $this->htmlEscape($_product->getDescription());
            $shortDescription = $this->htmlEscape($_product->getShortDescription());
            list($img, $thumb) = $helper->magicToolboxResizer($_product, 'image', 'category-thumb');

            $onclick = "";

            if ($tool->params->checkValue('disable-expand', 'Yes')) { //onclick only if MagicThumb disabled
                $onclick = 'onclick="document.location.href = \'' . $_product->getProductUrl() . '\';" ';
            } else {
                $onclick = '';
            }




            if($tool->params->checkValue('link-to-product-page', 'Yes')) {
                $link = $_product->getProductUrl();
            } else {

                $link = '';
            }


            $id = $_product->getId();
            $html = $tool->template(compact("id", "title", "description", "shortDescription", "img", "thumb", "link"));
            $html = preg_replace('/^<a /is', '<a ' . $onclick, $html);

            if($tool->params->checkValue('show-selectors-on-category-page', 'Yes')) {
                $gallery = Mage::getModel('catalog/product')->load($id)->getMediaGalleryImages();
                $html .= '<div class="MagicToolboxSelectorsContainer">';
                foreach($gallery  as $_image) {
                    list($img, $medium) = $helper->magicToolboxResizer($_product, 'image', 'category-thumb', $_image->getFile());
                    list($img, $thumb) = $helper->magicToolboxResizer($_product, 'image', 'category-selector', $_image->getFile());
                    $title = $this->htmlEscape($_image->getLabel());
                    $a = $tool->subTemplate(compact("id", "img", "thumb", "medium", "title"));
                    $html .= $a;
                }
                $html .= '</div>';
            }

            $html = '<div class="MagicToolboxContainer">' . $html . '</div>';

            $pattern = '<a[^>]+href=\"' . preg_quote($_product->getProductUrl(), '/') . '\"[^>]*>\s*<img[^>]+\/>\s*<\/a>';
            $pattern = '/' . $pattern . '/is';
            $contents_new = preg_replace($pattern, $html, $contents);
            if($contents_new == $contents) {
                $hash = preg_replace('/^.*?image\/([a-z0-9]+)\/.*$/is', '$1', $img);
                //$name = preg_replace('/^.*?image\/([a-z0-9]+)\/.*?\/([^\/]+)$/is', '$2', $img);
                $name = $this->helper('catalog/image')->init($_product, 'small_image');
                $name = preg_replace('/^.*?image\/([a-z0-9]+)\/.*?\/([^\/]+)$/is', '$2', $name);
                $pattern = '<img[^>]+src=\"[^\"]*\/' . preg_quote($hash, '/') . '\/[^\"]*\/' . preg_quote($name, '/') . '\"[^>]*\/>';
                //$pattern = '/' . $pattern . '/is';
                $contents_new = preg_replace('/<a[^>]+>\s*' . $pattern . '\s*<\/a>/is', $html, $contents);
                if($contents_new == $contents) {
                    $contents_new = preg_replace('/' . $pattern . '/is', $html, $contents);
                }
            }
            $contents = $contents_new;
        }
    }

?>
