<?php

/**
 * Magictoolbox new products list template for Magento store.
 * Allow use MagicTools on product list page.
 * @mail support@magictoolbox.com
 */

$_productCollection = $this->getProductCollection();

if ($_productCollection && $_productCollection->getSize()) {

    $helper = Mage::helper('magiczoomplus/settings');
    $tool = $helper->loadTool('category');
    if($tool->params->checkValue('use-effect-on-category-page', 'Yes')) {

        ob_start();
        require($helper->getProductsNewTemplateFilename());
        $contents = ob_get_contents();
        ob_end_clean();
        require($helper->getMagicToolboxListTemplateFilename());
        echo $contents;

    } else {

        require($helper->getProductsNewTemplateFilename());
    }

}

?>
